In [1]:
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
from bs4 import BeautifulSoup
import requests
import time
from selenium.common.exceptions import ElementNotVisibleException
import re
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException,InvalidArgumentException,InvalidCookieDomainException

# Answer - 1

In [2]:
url =  'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-2-83351a870014>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
rank =[]
name =[]
artist = []
views = []
date = []

In [4]:
for i in range(1,31):
    num_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
    try:
      rank.append(num_tag.text)
    except NoSuchElementException:
      rank.append("-")
       
for i in range(1,31):
    vid_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
    try:
        name.append(vid_tag.text.strip().split('"')[1]) #appending only the names of the videos
    except NoSuchElementException:
        name.append("-")
 
for i in range(1,31):
    uploadr_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
    try:
        artist.append(uploadr_tag.text)
    except NoSuchElementException:
        artist.append("-")
        
for i in range(1,31):
    views_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
    try:
        views.append(views_tag.text)
    except NoSuchElementException:
        views.append("-")
        
        
for i in range(1,31):
    date_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")
    try:
        date.append(date_tag.text)
    except NoSuchElementException:
        date.append("-")

top_youtube_vids = {"Rank":rank,"Name":name,"Artist":artist,"Upload Date":date,"Views(Billions)":views}
Most_Viewed_Videos = pd.DataFrame(top_youtube_vids)

<ipython-input-4-78da50d2b58f>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  num_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
<ipython-input-4-78da50d2b58f>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  vid_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
<ipython-input-4-78da50d2b58f>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  uploadr_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
<ipython-input-4-78da50d2b58f>:23: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  views_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
<ipython-input-4-78da50d2b58f>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  date_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")

In [5]:
Most_Viewed_Videos

,Rank,Name,Artist,Upload Date,Views(Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.90
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.68
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.06
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.57
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.37
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.79
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.54
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.48
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.41
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.37
10,11.,Gangnam Style,Psy,"July 15, 2012",4.29
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.77
12,13.,Sugar,Maroon 5,"January 14, 2015",3.61
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.50
14,15.,Roar,Katy Perry,"September 5, 2013",3.49
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.47
16,17.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.44
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.38
18,19.,Girls Like You,Maroon 5,"May 31, 2018",3.20
19,20.,Faded,Alan Walker,"December 3, 2015",3.20
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.20
21,22.,Axel F,Crazy Frog,"June 16, 2009",3.15
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.14
23,24.,Let Her Go,Passenger,"July 25, 2012",3.14
24,25.,Lean On,Major Lazer,"March 22, 2015",3.14
25,26.,Shake It Off,Taylor Swift,"August 18, 2014",3.13
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.05
27,28.,Mi Gente,J Balvin,"June 29, 2017",3.02
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.02
29,30.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.01

# Answer - 2

In [18]:
url =  'https://www.bcci.tv/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-18-1e34496256d0>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [33]:
intbtn = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
try:
    intbtn.click() #clicking on International button
except ElementNotInteractableException:
    pass
     
fixbtn =  driver.find_element_by_xpath('/html/body/div[3]/div[1]/ul/li[1]')
try: 
    fixbtn.click() #clicking on Fixtures button
except ElementNotInteractableException:
    pass

<ipython-input-33-a7b8a10c5dfe>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  intbtn = driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
<ipython-input-33-a7b8a10c5dfe>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  fixbtn =  driver.find_element_by_xpath('/html/body/div[3]/div[1]/ul/li[1]')

In [35]:
Match_title = []
Series = []
Place = []
Date = []
Month=[]
Time = []

In [36]:
Match_title_tag = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
Series_tag = driver.find_elements_by_xpath("//div[@class='fixture__format-strip']")
Place_tag = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
Date_tag = driver.find_elements_by_xpath("//span[@class='fixture__date']")
Month_tag=driver.find_elements_by_xpath("//span[@class='fixture__month']")

<ipython-input-36-3e0bc2774b99>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Match_title_tag = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
<ipython-input-36-3e0bc2774b99>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Series_tag = driver.find_elements_by_xpath("//div[@class='fixture__format-strip']")
<ipython-input-36-3e0bc2774b99>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Place_tag = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
<ipython-input-36-3e0bc2774b99>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Date_tag = driver.find_elements_by_xpath("//span[@class='fixture__date']")
<ipython-input-36-3e0bc2774b99>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Month_tag=driver.find_elements_by_xpath("//span[@class='fixture__month']")

In [37]:
for m in Match_title_tag:
    try:
        Match_title.append(m.text)
    except NoSuchElementException:
        Match_title.append("-")
for s in Series_tag:
    try:
        Series.append(s.text.replace("\n"," "))
    except NoSuchElementException:
        Series.append("-")
        
for p in Place_tag:
    try:
        Place.append(p.text)
    except NoSuchElementException:
        Place.append("-")
        
for d in Date_tag:
    try:
        Date.append(d.text)
    except NoSuchElementException:
        Date.append("-")
for m in Month_tag:
    try:
        Month.append(m.text)
    except NoSuchElementException:
        Month.append("-")

In [38]:
url=[]
url_tag=driver.find_elements_by_xpath("//div[@class='js-list']/a")
for i in url_tag:
    url.append(i.get_attribute("href"))

<ipython-input-38-04fa13a2f1dd>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  url_tag=driver.find_elements_by_xpath("//div[@class='js-list']/a")

In [39]:
len(url)

0

In [40]:
Time=[]
for i in url:
    driver.get(i)
    time.sleep(3)
    Time_tag=driver.find_element_by_xpath("//span[@class='mc-header-scorebox__ist-time']")
    try:
        Time.append(Time_tag.text)
    except NoSuchElementException:
        Time.append("-")

In [41]:
Full_Date=[]
for (item1,item2) in zip(Date,Month):
    Full_Date.append(item1+item2)

In [42]:
print(len(Time),len(Match_title),len(Series),len(Place),len(Full_Date))

0 0 0 0 0

In [43]:
cricket = {'Match Title': Match_title,'Series':Series,'Place':Place,'Date':Full_Date,'Time':Time}

In [44]:
Cricket=pd.DataFrame(cricket)

In [45]:
Cricket

Empty DataFrame
Columns: [Match Title, Series, Place, Date, Time]
Index: []

# Answer - 3

In [46]:
url =  'https://www.guru99.com/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-46-e01e021723c5>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [47]:
selbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
try:
    selbtn.click() #clicking on Selenium button
except ElementNotInteractableException:
    pass
     
tutbtn =  driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
try: 
    tutbtn.click() #clicking on Exceptions Tutorial button
except ElementNotInteractableException:
    pass

<ipython-input-47-199655db7ae5>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  selbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
<ipython-input-47-199655db7ae5>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  tutbtn =  driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')

In [48]:
Name = []
desc = []

In [49]:
for i in range(2,43):
    Name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
    try:
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
for i in range(2,43):    
    desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")
    try:
        desc.append(desc_tag.text)
    except NoSuchElementException:
        desc.append("-")

<ipython-input-49-3f1864b37f57>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
<ipython-input-49-3f1864b37f57>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")

In [50]:
Excep = {'Name': Name,'Description':desc}

In [51]:
Exception = pd.DataFrame(Excep)
Exception

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# Answer - 4

In [52]:
url =  'http://statisticstimes.com/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-52-52be7ff04b83>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [54]:
Eco_btn=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button") #economy button
try:
    Eco_btn.click()#click economy button
except ElementNotInteractableException:
    pass

ind=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")#India button
try:
    ind.click()#click India button
except ElementNotInteractableException:
    pass

<ipython-input-54-98a725dfa0ba>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Eco_btn=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button") #economy button
<ipython-input-54-98a725dfa0ba>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  ind=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")#India button

In [56]:
indstate=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")#GDP of Indian states
try:
    indstate.click()#click button
except ElementNotInteractableException:
    pass

<ipython-input-56-537c7363ea5a>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  indstate=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")#GDP of Indian states

In [57]:
Rank = []
State = []
GSDP_19 = []
GSDP_18 = []
Share_18 = []
GDP = []

In [58]:
for i in range(1,34):
    rank_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
    try:
        Rank.append(rank_tag.text)
    except NoSuchElementException:
        Rank.append("-")
for i in range(1,34):
    State_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
    try:
        State.append(State_tag.text)
    except NoSuchElementException:
        State.append("-")
        
for i in range(1,34):
    GSDP_19_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
    try:
        GSDP_19.append(GSDP_19_tag.text)
    except NoSuchElementException:
        GSDP_19.append("-")

for i in range(1,34):
    GSDP_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
    try:
        GSDP_18.append(GSDP_18_tag.text)
    except NoSuchElementException:
        GSDP_18.append("-")

for i in range(1,34):
    Share_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
    try:
        Share_18.append(Share_18_tag.text)
    except NoSuchElementException:
        Share_18.append("-")
for i in range(1,34):
    GDP_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")
    try:
        GDP.append(GDP_tag.text)
    except NoSuchElementException:
        GDP.append("-")

<ipython-input-58-ebf01a67bf0e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  rank_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
<ipython-input-58-ebf01a67bf0e>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  State_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
<ipython-input-58-ebf01a67bf0e>:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GSDP_19_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
<ipython-input-58-ebf01a67bf0e>:22: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GSDP_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
<ipython-input-58-ebf01a67bf0e>:29: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Share_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
<ipython-input-58-ebf01a67bf0e>:35: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GDP_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")

In [59]:
GDP = {'Rank': Rank,'State':State,'GSDP at current price(19-20)':GSDP_19,'GSDP at current price(18-19)':GSDP_18,'Share(18-19)':Share_18,'GDP($ billion)':GDP}

In [60]:
GDPIND = pd.DataFrame(GDP)
GDPIND

,Rank,State,GSDP at current price(19-20),GSDP at current price(18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Answer - 5

In [61]:
url =  'https://github.com/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-61-7cba49c3a9e0>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [62]:
Exp_btn=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary") #explore button
try:
    Exp_btn.click()#click explore button
except ElementNotInteractableException:
    pass
trnd=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")#Trending button
try:
    trnd.click()#click Trending button
except ElementNotInteractableException:
    pass

<ipython-input-62-7453f4ff01f8>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Exp_btn=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary") #explore button
<ipython-input-62-7453f4ff01f8>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  trnd=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")#Trending button

In [63]:
title = []
desc = []
count = []
url = []

In [64]:
title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

<ipython-input-64-cebc8138ba4d>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [65]:
for r in title_tag:
    try:
       url.append(r.get_attribute("href"))
    except NoSuchElementException:
        url.append("-")

In [66]:
title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

<ipython-input-66-cebc8138ba4d>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [67]:
for r in title_tag:
    try:
        title.append(r.text)
    except NoSuchElementException:
        title.append("-")

In [68]:
len(title)

25

In [69]:
for i in url:
    driver.get(i)
    time.sleep(5)
    try:   
        desc_tag = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        desc.append(desc_tag.text)
    except NoSuchElementException:
        desc.append('-')
    try:
        count_tag = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")
        count.append(count_tag.text)
    except NoSuchElementException:
        count.append('-')

<ipython-input-69-961a0165e5cb>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc_tag = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
<ipython-input-69-961a0165e5cb>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  count_tag = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")

In [70]:
lng = []

In [71]:
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        lng_tag = driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]")
        lng.append(lng_tag.text)
    except NoSuchElementException:
        lng.append('-')

<ipython-input-71-5694858f47c0>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  lng_tag = driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]")

In [72]:
git = {'Repository title': title,'Repository description':desc,'Contributors count':count,'Language used':lng}

In [73]:
Git = pd.DataFrame(git)

In [74]:
Git

,Repository title,Repository description,Contributors count,Language used
0,mkrl / misbrands,-,-,-
1,babysor / MockingBird,-,19,JavaScript
2,mpcabete / bombcrypto-bot,-,9,Python
3,TeamNewPipe / NewPipe,-,635,Java
4,marktext / marktext,-,117,JavaScript
5,donnemartin / system-design-primer,-,111,Python
6,zeldaret / oot,-,65,C
7,airbnb / javascript,-,481,JavaScript
8,teslamotors / light-show,-,2,Python
9,alesimula / wsa_pacman,-,2,Dart
10,Courseplay / Courseplay_FS22,-,15,Lua
11,cisagov / log4j-scanner,-,3,Java
12,dair-ai / ML-YouTube-Courses,-,2,-
13,R2Northstar / Northstar,-,-,-
14,bitcoin / bitcoin,-,847,C++
15,R2Northstar / NorthstarMods,-,-,Squirrel
16,trekhleb / javascript-algorithms,-,143,JavaScript
17,gto76 / python-cheatsheet,-,11,Python
18,freeCodeCamp / LearnToCodeRPG,-,6,Ren'Py
19,sindresorhus / awesome,-,512,-
20,mtdvio / every-programmer-should-know,-,71,-
21,30-seconds / 30-seconds-of-code,-,264,JavaScript
22,awesome-selfhosted / awesome-selfhosted,-,979,JavaScript
23,JustArchiNET / ArchiSteamFarm,-,34,C#
24,Tencent / tdesign-vue-next,-,67,TypeScript

# Answer - 6

In [84]:
url =  'https://www.billboard.com/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-84-89821e357f76>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [85]:
top100_btn=driver.find_element_by_xpath("/html/body/div[4]/header/div[2]/div/nav/ul/li[1]/a") #hot100 button
try:
    top100_btn.click()#click explore button
except ElementNotInteractableException:
    pass

<ipython-input-85-cd397a408f2b>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  top100_btn=driver.find_element_by_xpath("/html/body/div[4]/header/div[2]/div/nav/ul/li[1]/a") #hot100 button

In [86]:
#scraping Last week rank
last_week=[]
try:
    L_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in L_tag:
        last_week.append(i.text)
except NoSuchElementException:#handling no such element exception
    last_week.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    last_week.append('No details available')

<ipython-input-86-2c20f727258d>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  L_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")

In [87]:
name=[]
#scraping song name
try:
    n_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in n_tag:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    name.append('No details available')

<ipython-input-87-3990caf56952>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  n_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")

In [88]:
artist=[]
#scraping artist name
try:
    a_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in a_tag:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    artist.append('No details available')

<ipython-input-88-649bb4ddd65d>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  a_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")

In [89]:
peak_rank=[]
#scraping peak rank
try:
    p_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in p_tag:
        peak_rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    peak_rank.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    peak_rank.append('No details available')

<ipython-input-89-7aa682cd4dbf>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  p_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")

In [90]:
week=[]
#scraping weeks on board
try:
    w_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in w_tag:
        week.append(i.text)
except NoSuchElementException:#handling no such element exception
    week.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    week.append('No details available')

<ipython-input-90-c45e4554c0b2>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  w_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")

In [91]:
df = pd.DataFrame({'song name':name,'Artist_name':artist,'Last week rank':last_week,'Peak rank':peak_rank,'Weeks on board':week})
Top_100_Songs=df[:100]
Top_100_Songs

Empty DataFrame
Columns: [song name, Artist_name, Last week rank, Peak rank, Weeks on board]
Index: []

# Answer - 7

In [92]:
url =  'https://www.naukri.com/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-92-c1c9b9e0b1b8>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [93]:
recruit_btn=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div") #recruiters button
try:
    recruit_btn.click()#click recruiters button
except ElementNotInteractableException:
    pass
driver.switch_to.window(driver.window_handles[1])#switch to recruiters tab

<ipython-input-93-332f344499ad>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  recruit_btn=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div") #recruiters button

In [94]:
jobsearch = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
jobsearch

<ipython-input-94-e7a6ff30f764>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  jobsearch = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')

In [95]:
jobsearch.send_keys("Data science")

In [96]:
srchbtn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
srchbtn.click()

<ipython-input-96-9efe354a009f>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  srchbtn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')

In [97]:
Name = []
Designation = []
Company = []
Skills = []

In [98]:
Name_tag = driver.find_elements_by_xpath("//a[@class='ellipsis']/span")
Designation_tag = driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
Company_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
Skills_tag = driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
Location_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/span/small")

<ipython-input-98-c422f168d8c0>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Name_tag = driver.find_elements_by_xpath("//a[@class='ellipsis']/span")
<ipython-input-98-c422f168d8c0>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Designation_tag = driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
<ipython-input-98-c422f168d8c0>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Company_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
<ipython-input-98-c422f168d8c0>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Skills_tag = driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
<ipython-input-98-c422f168d8c0>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Location_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/span/small")

In [99]:
for n in Name_tag:
    try:
        Name.append(n.text)
    except NoSuchElementException:
        Name.append("-")
for d in Designation_tag:
    try:
        Designation.append(d.text)
    except NoSuchElementException:
        Designation.append("-")


for c in Company_tag:
    try:
        Company.append(c.text)
    except NoSuchElementException:
        Company.append("-")


for s in Skills_tag:
    try:
        Skills.append(s.text)
    except NoSuchElementException:
        Skills.append("-")

In [100]:
nameurl = []

In [101]:
name_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")

<ipython-input-101-cae30aaffeb4>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")

In [102]:
for r in name_tag:
    try:
       nameurl.append(r.get_attribute("href"))
    except NoSuchElementException:
        nameurl.append("-")

In [103]:
Location = []

In [104]:
for i in nameurl:
    driver.get(i)
    time.sleep(5)
    try:   
        Location_tag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")
        Location.append(Location_tag.text)
    except NoSuchElementException:
        Location.append('-')

<ipython-input-104-c1c707c7be6d>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Location_tag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")

In [105]:
jobs = {'Name': Name,'Designation':Designation,'Company':Company,'Skills they hire for':Skills,'Location':Location}

Jobs = pd.DataFrame(jobs)

Jobs

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
30,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
32,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
34,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad

# Answer - 8

In [106]:
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

<ipython-input-106-15202a3d05e0>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [107]:
url = ("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
driver.get(url)
time.sleep(3)

In [108]:
# creating empty lists
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []


# scraping book names data
for i in driver.find_elements_by_xpath("//tbody//tr//td[2]"):
    Book_name.append(i.text)

    
# scraping author names data
for i in driver.find_elements_by_xpath("//tbody//tr//td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(3)


# scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody//tr//td[4]"):
    Volumes_sold.append(i.text)
    
    
# scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody//tr//td[5]"):
    Publisher.append(i.text)
    
    
# scraping  data of genre
for i in driver.find_elements_by_xpath("//tbody//tr//td[6]"):
    Genre.append(i.text)    
    
    
# creating dataframe for scraped data
Novels = pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

<ipython-input-108-b6a8a4b6dddb>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//tbody//tr//td[2]"):
<ipython-input-108-b6a8a4b6dddb>:15: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//tbody//tr//td[3]"):
<ipython-input-108-b6a8a4b6dddb>:25: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//tbody//tr//td[4]"):
<ipython-input-108-b6a8a4b6dddb>:30: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//tbody//tr//td[5]"):
<ipython-input-108-b6a8a4b6dddb>:35: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//tbody//tr//td[6]"):

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Answer-9

In [109]:
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

<ipython-input-109-15202a3d05e0>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [110]:
url = ("https://www.imdb.com/list/ls095964455/")
driver.get(url)

In [111]:
# creating empty lists
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

# scraped data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
    
# scraped data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
    
# scraped data of Genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)
    
    
# scraped data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)
    
    
# scraped data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
    
# scraped data of Votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text) 
    
    
# creating dataframe for scraped data
TV_Series = pd.DataFrame({})
TV_Series['Name'] = Name
TV_Series['Year Span'] = Year_span
TV_Series['Genre'] = Genre
TV_Series['Run Time'] = Run_time
TV_Series['Ratings'] = Ratings
TV_Series['Votes'] = Votes
TV_Series

<ipython-input-111-3054a3bdee06>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
<ipython-input-111-3054a3bdee06>:15: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
<ipython-input-111-3054a3bdee06>:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='genre']"):
<ipython-input-111-3054a3bdee06>:25: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
<ipython-input-111-3054a3bdee06>:30: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
<ipython-input-111-3054a3bdee06>:35: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,919,320"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"944,248"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"918,461"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"274,995"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"235,378"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,895"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,690"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"181,922"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,029"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"216,089"

# Answer - 10

In [112]:
url =  'https://archive.ics.uci.edu/'
driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")
driver.get(url)

<ipython-input-112-4370104a63b6>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\lenovo\Downloads\chromedriver_win32\chromedriver.exe")

In [113]:
dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') #view all data sets button
try:
    dtbtn.click() #clicking on view all data sets button
except ElementNotInteractableException:
    pass

<ipython-input-113-2953cdfaaa09>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') #view all data sets button

In [114]:
Name = []
Datatype = []
Task = []
Attribute = []
instances = []
attribute_no = []
Year = []

In [115]:
for i in range(1,590):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
        
for i in range(1,590):
    try:
        Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
        Datatype.append(Datatype_tag.text)
    except NoSuchElementException:
        Datatype.append("-")
        
for i in range(1,590):
    try:
        Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
        Task.append(Task_tag.text)
    except NoSuchElementException:
        Task.append("-")

for i in range(1,590):
    try:
        Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
        Attribute.append(Attribute_tag.text)
    except NoSuchElementException:
        Attribute.append("-")

for i in range(1,590):
    try:
        instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
        instances.append(instances_tag.text)
    except NoSuchElementException:
        instances.append("-")
for i in range(1,590):
    try:
        attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
        attribute_no.append(attribute_no_tag.text)
    except NoSuchElementException:
        Votes.append("-")
for i in range(1,590):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")

<ipython-input-115-1132c95f86d6>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
<ipython-input-115-1132c95f86d6>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
<ipython-input-115-1132c95f86d6>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
<ipython-input-115-1132c95f86d6>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
<ipython-input-115-1132c95f86d6>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
<ipython-input-115-1132c95f86d6>:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
<ipython-input-115-1132c95f86d6>:43: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")

In [116]:
repo = {'Dataset name': Name,'Data type':Datatype,'Task':Task,'Attribute type':Attribute,'No of instances':instances,'No of attribute':attribute_no,'Year':Year}

RepoDF = pd.DataFrame(repo)
RepoDF.drop(index = 0,inplace = True)

In [117]:
RepoDF

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
584,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
585,Gait Classification,Multivariate,Classification,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021

# Thank You